from gpiozero import AngularServo
from time import sleep

class ServoController:
    def __init__(self, pin, min_angle=-90, max_angle=90, min_pulse=0.0005, max_pulse=0.0025):
        self.servo = AngularServo(pin,
                                  min_angle=min_angle,
                                  max_angle=max_angle,
                                  min_pulse_width=min_pulse,
                                  max_pulse_width=max_pulse)

    def move_to_angle(self, angle):
        """Clamp and move directly to the target angle."""
        angle = max(self.servo.min_angle, min(self.servo.max_angle, angle))
        self.servo.angle = angle
        sleep(0.4)

    def detach(self):
        self.servo.detach()

# Create instances for two servos
servo1 = ServoController(pin=13)
servo2 = ServoController(pin=12)

try:
    sleep(1)  # Initial delay

    # Move servo1 first
    servo1.move_to_angle(90)
    #sleep(2)
    servo1.move_to_angle(-90)
    #sleep(2)
    servo1.move_to_angle(45)
    #sleep(2)
    servo1.move_to_angle(-45)
    #sleep(2)
    servo1.move_to_angle(0)
    servo1.move_to_angle(90)
    #sleep(2)
    servo1.move_to_angle(-90)
    #sleep(2)
    servo1.move_to_angle(45)
    #sleep(2)
    servo1.move_to_angle(-45)
    #sleep(2)
    servo1.move_to_angle(0)
    servo1.move_to_angle(90)
    #sleep(2)
    servo1.move_to_angle(-90)
    #sleep(2)
    servo1.move_to_angle(45)
    #sleep(2)
    servo1.move_to_angle(-45)
    #sleep(2)
    servo1.move_to_angle(0)
    servo1.move_to_angle(90)
    #sleep(2)
    servo1.move_to_angle(-90)
    #sleep(2)
    servo1.move_to_angle(45)
    #sleep(2)
    servo1.move_to_angle(-45)
    #sleep(2)
    servo1.move_to_angle(0)
    servo1.move_to_angle(90)
    #sleep(2)
    servo1.move_to_angle(-90)
    #sleep(2)
    servo1.move_to_angle(45)
    #sleep(2)
    servo1.move_to_angle(-45)
    #sleep(2)
    servo1.move_to_angle(0)
    servo1.move_to_angle(90)
    #sleep(2)
    servo1.move_to_angle(-90)
    #sleep(2)
    servo1.move_to_angle(45)
    #sleep(2)
    servo1.move_to_angle(-45)
    #sleep(2)
    servo1.move_to_angle(0)
    servo1.move_to_angle(90)
    #sleep(2)
    servo1.move_to_angle(-90)
    #sleep(2)
    servo1.move_to_angle(45)
    #sleep(2)
    servo1.move_to_angle(-45)
    #sleep(2)
    servo1.move_to_angle(0)
    servo1.move_to_angle(90)
    #sleep(2)
    servo1.move_to_angle(-90)
    #sleep(2)
    servo1.move_to_angle(45)
    #sleep(2)
    servo1.move_to_angle(-45)
    #sleep(2)
    servo1.move_to_angle(0)
    servo1.move_to_angle(90)
    #sleep(2)
    servo1.move_to_angle(-90)
    #sleep(2)
    servo1.move_to_angle(45)
    #sleep(2)
    servo1.move_to_angle(-45)
    #sleep(2)
    servo1.move_to_angle(0)
    servo1.move_to_angle(90)
    #sleep(2)
    servo1.move_to_angle(-90)
    #sleep(2)
    servo1.move_to_angle(45)
    #sleep(2)
    servo1.move_to_angle(-45)
    #sleep(2)
    servo1.move_to_angle(0)
    servo1.move_to_angle(90)
    #sleep(2)
    servo1.move_to_angle(-90)
    #sleep(2)
    servo1.move_to_angle(45)
    #sleep(2)
    servo1.move_to_angle(-45)
    #sleep(2)
    servo1.move_to_angle(0)
    

    # Then move servo2
    servo2.move_to_angle(30)
    servo2.move_to_angle(90)
    #sleep(2)
    servo2.move_to_angle(90)
    #sleep(2)
    servo2.move_to_angle(45)
    #sleep(2)
    servo2.move_to_angle(45)
    #sleep(2)
    servo2.move_to_angle(0)
    servo2.move_to_angle(30)
    servo2.move_to_angle(90)
    #sleep(2)
    servo2.move_to_angle(90)
    #sleep(2)
    servo2.move_to_angle(45)
    #sleep(2)
    servo2.move_to_angle(45)
    #sleep(2)
    servo2.move_to_angle(0)
    servo2.move_to_angle(30)
    servo2.move_to_angle(90)
    #sleep(2)
    servo2.move_to_angle(90)
    #sleep(2)
    servo2.move_to_angle(45)
    #sleep(2)
    servo2.move_to_angle(45)
    #sleep(2)
    servo2.move_to_angle(0)
    servo2.move_to_angle(30)
    servo2.move_to_angle(90)
    #sleep(2)
    servo2.move_to_angle(90)
    #sleep(2)
    servo2.move_to_angle(45)
    #sleep(2)
    servo2.move_to_angle(45)
    #sleep(2)
    servo2.move_to_angle(0)
    servo2.move_to_angle(30)
    servo2.move_to_angle(90)
    #sleep(2)
    servo2.move_to_angle(90)
    #sleep(2)
    servo2.move_to_angle(45)
    #sleep(2)
    servo2.move_to_angle(45)
    #sleep(2)
    servo2.move_to_angle(0)
    servo2.move_to_angle(30)
    servo2.move_to_angle(90)
    #sleep(2)
    servo2.move_to_angle(90)
    #sleep(2)
    servo2.move_to_angle(45)
    #sleep(2)
    servo2.move_to_angle(45)
    #sleep(2)
    servo2.move_to_angle(0)

finally:
    servo1.detach()
    servo2.detach()
